### ISSUE TITLE
Stream getting errors now?

### ISSUE THREAD

**Issue by asad-awadia** [torfsen/roux-stream#10]
`decoding response body: expected value at line 1 column 1`

getting errors like this now all the time? not sure what to print to see the actual response body

@torfsen

**Comment by torfsen** [comment]
Thanks for your report, @asad-awadia. I think this is an upstream issue in `roux`, in particular halcyonnouveau/roux#65.

It should be fixed in `roux` `2.2.7`. Note that `roux-stream` currently does not support `roux` `2`, yet (see #6).

**Comment by asad-awadia** [comment]
@torfsen 
what to do in the mean time? any work around?

What is blocking roux-stream from supporting roux 2?
