### ISSUE TITLE
roux_stream is incompatible with roux v2.0.0 and higher.

### ISSUE THREAD

**Issue by ChecksumDev** [torfsen/roux-stream#6]
The examples provided in the [docs](https://docs.rs/roux-stream/latest/roux_stream/fn.stream_submissions.html) are not compatible with the latest version of roux, the highest version which is compatible is `v1.4.0`.

![image](https://user-images.githubusercontent.com/24845326/187226897-ed557735-e20b-42cb-ac59-a997b960a025.png)

**Comment by archae0pteryx** [comment]
Even when i downgrade i seem to have this issue. maybe i'm missing something. +1 over here though.

**Comment by asad-awadia** [comment]
would this require a lot of changes?

**Comment by asad-awadia** [comment]
https://github.com/torfsen/roux-stream/pull/11

**Comment by torfsen** [comment]
Fixed by #7 but not yet released.

**Comment by torfsen** [comment]
Released in `0.2.0`.
